Add integration test for sending from swap
utxo-teleport/teleport-transactions pull request #95
Opened 2024-02-14 07:49 UTC by QureshiFaisal

This is in reference to issue #93 
1. Refer to the `send_from_swap.rs` in `tests`.
2. Kindly verify the logic for swapping coins between a taker & maker, asserting balances, listing UTXOs from the taker's wallet, creating a transaction and signing it.
3. I am unable to figure out the logic for broadcasting the signed transaction.

2024-02-17 16:04 UTC, rajarshimaitra commented
Concept ACK.. reviewing soon..

2024-02-25 16:03 UTC, rajarshimaitra requested changes
Good attempt. But needs more work. 

Remove the usual checks already covered in standard swap. Filter one swapcoin from the list unspent and list and try to spend only that input. 

Broadcast the tx after signing. 

Confirm the tx. Then check that the new tx also appeared in the listunpsent output. Assert the wallet final balance with expected balance.

2024-02-28 12:45 UTC, QureshiFaisal commented on tests/send_from_swap.rs
> +    .unwrap();
Here I collect all the unspent utxos, right below this I choose the txid and vout of the first transaction i.e `utxo_outpoint` to use only that specific transaction. So, I'm passing only one utxo from the list to `create_direct_send`

2024-02-29 07:12 UTC, QureshiFaisal commented on tests/send_from_swap.rs
> +    .collect();
`sign_transaction` needs a vector that iterates over `UTXOspendinfo` and thus I have created that vector in `unspent_inputs`

2024-02-29 07:12 UTC, QureshiFaisal commented on tests/send_from_swap.rs
> +
This is the new broadcast logic

2024-02-29 13:24 UTC, rajarshimaitra requested changes
Few more comments. 

Also, run `cargo fmt` to get the formatting sorted.

2024-02-29 13:24 UTC, rajarshimaitra commented on tests/send_from_swap.rs
> +    .collect();
If you just pass in `[spend_info]` that will work.

2024-02-29 13:24 UTC, rajarshimaitra commented on tests/send_from_swap.rs
> +    .unwrap();
How do you ensure that the first coin is always a swapcoin? Could be a seedcoin or fidelitycoin too. Later on also we are not checking if we are spending a swapcoin or some other kind of coin.

That needs to be checked here. And the way to do that is use `find` on the list_unspent result where spend_info == SwapCoin. 

You can use `matches!()` macro inside `find` to match the `spend_info` variable with a `SwapCoin` structure.

2024-02-29 13:24 UTC, rajarshimaitra commented on tests/send_from_swap.rs
> +println!("Transaction broadcasted successfully. Transaction ID: {}", txid);
The rpc client is already available in the `test_framework` variable. Just do `test_framework.bitcoind.client`. You don't have to recreate a new client.

2024-02-29 13:24 UTC, rajarshimaitra commented on tests/send_from_swap.rs
> +}
let's assert the exact balance here, not the below-ness.

2024-03-13 09:44 UTC, closed without merging